version: '3'
services:

  cms:
    build: .
    environment:
      - MONGO_URI=mongodb://db/lucky-day-gaming
      - COOKIE_SECRET=chocolate-chips-haha-get-it
      - PORT=3000
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
    ports:
      - 3000:3000

  db:
    image: mongo
